### ISSUE TITLE
Report confirmationsRequired for pending txns in `multisig-transactions/{safe_tx}`

### ISSUE THREAD

**Issue by DefiDebauchery** [safe-global/safe-transaction-service#1148]
# What is needed?
Pending transactions do not currently report the number of confirmations required for execution. This would be incredibly helpful to determine how far along a given `safe_tx` is without doing a separate call, which is unneeded.

Since the model stores the `threshold`, this doesn't seem to be a terribly expensive query to make.

# Endpoint
`/api/v1/multisig-transactions/{safe_tx}`

**Comment by Uxio0** [comment]
The `MultisigTransaction` model does not store the `threshold`, where do you see that? Please do a separate call in your app and keep the information about the threshold

**Comment by DefiDebauchery** [comment]
So how/where is it retrieved when viewing an executed transaction? Why would it not be the same?

**Comment by Uxio0** [comment]
> So how/where is it retrieved when fetching an executed transaction? Why would it not be the same?

I get you now, I was confused by `Since the model stores the threshold, this doesn't seem to be a terribly expensive query to make.`. I didn't remember that we didn't include the `threshold` for non executed transactions, we will reevaluate this. I was checking the code and I understand now why it was a little hacky to get that information.

Thanks for sharing, in the meantime as I said just do a separate call, we will update this issue
