### ISSUE TITLE
Refactor sending events to RabbitMQ

### ISSUE THREAD

**Issue by Uxio0** [safe-global/safe-transaction-service#1814]
# What is needed?
We should study how to send events to RabbitMQ in a more optimal way.

# Background
Sometimes when there're a lot of events they get stuck and never get sent or they are sent with delay.

Things that we could check:
- Using the right RabbitMQ library
- Maybe even using the right library gevent is not working propertly
- Sending the events directly to RabbitMQ instead of sending them to a Celery queue and then to Rabbit

**Comment by moisses89** [comment]
After several tests looks like the issue is that `gevent` is not working properly with `Pika + celery` when we have high volume of events/tasks. 
###  Connection issues
Connection collisions betweeen `greenlets`, I'm guessing here that the socket collision is between the `Pika greenlet` and `celery`, the following issue appears at the same time that connection issues appear with `RabbitMQ`. 
`ConcurrentObjectUseError('This socket is already used by another greenlet: <bound method Waiter.switch of <gevent._gevent_c_waiter.Waiter object at 0xffff9d30a9d0>>')` 
### Events lost
We are using Pika in asynchronous way that means connection is handled in a gevent greenlet. 
After create a test that send (delayed with celery) 10.000 of events with an incremental id and forcing to close the client connection from `RabbitMQ` management, I could see that the disconnection event is delayed and several messages are sent without detect the connection issue, on subscriber side more or less 500 events were lost. 
### Delayed events
After several tries I can say that delayed events are because celery, send the 10.000 events directly without a celery task is clearly quickest.
