### ISSUE TITLE
[ API ] Get token logos from trusted lists

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#2103]
# What is needed?
Currently the logos need to be uploaded manually in the transaction service by the admin page. 
This is hard to manage when we need to update large quantity of tokens. 
My suggestion is take advantage of trusted lists that are configured in the service and get the logos from there when there is not any logo upload for the token. 
At this way the service would need less maintenance updating tokens logos. 

Example of list: https://tokens.coingecko.com/uniswap/all.json.

**Comment by Uxio0** [comment]
FYI @hectorgomezv we will implement this but this images logic should be moved to wallet side

**Comment by hectorgomezv** [comment]
> FYI @hectorgomezv we will implement this but images logic should be moved to wallet side

It makes total sense to me 👍🏻

**Comment by falvaradorodriguez** [comment]
We analysed this task and found some problems:

The images that come in the token list are generally of very bad quality, so they would not contribute much to the website.

The task is not as straightforward as we thought in the first approach. We need to rethink the backup mechanism in S3 of the logos to integrate these logos because we shouldn't download the logos from the URLs as we shouldn't trust the content of these URLs. This implies saving the URL and returning it in the endpoint response which implies modifying the priority of the S3 backup mechanism

For these reasons, we will be closing this task for now.

**Comment by Uxio0** [comment]
The number of logos that we need to add manually is highly increasing, so it's better at this point to load them from the trusted lists. In case quality is not good token creators should handle that with the list maintainer
