### ISSUE TITLE
Diff versions are returned for the same mastercopy address on xDai

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-transaction-service#864]
These two safes have the same mastercopy "0x3E5c63644E683549055b9Be8653de26E0B4CD36E" but different version ( 1.3.0 and 1.3.0+L2)
https://safe-transaction.xdai.gnosis.io/api/v1/safes/0xf8fFe7717372641ec2123fc81ACF7c71cbeA24aA/
https://safe-transaction.xdai.gnosis.io/api/v1/safes/0x6A0491132aF4d0925F857A5000bb21e5C5C195EA/
The issue leads to the different labels on the mobile client for the same mastercopy address

**Comment by Uxio0** [comment]
For some Safes when a correct state is not found, we go for blockchain, that's why we get the version returned from the master copy. We should return the same information in both requests. 

@safe-global/safe-services what do you think?

- Going for using the backend version for everything, with meta information (e.g. `1.3.0+L2`). This is my favourite
- Going for the blockchain version for everything (e.g. `1.3.0`)
